<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <IsPackable>False</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EventFlow\EventFlow.csproj" />
    <ProjectReference Include="..\EventFlow.DeclarativeSaga\EventFlow.DeclarativeSaga.csproj" />
  </ItemGroup>
</Project>
